# Generated by Django 3.2.16 on 2022-11-14 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('deadline',), 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
